// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcY5GjBFaJ-swvEJHBGsTiTE1qbumHIco',
    appId: '1:162639628951:web:aa90df6b0da482942637d2',
    messagingSenderId: '162639628951',
    projectId: 'lifematters-c466d',
    authDomain: 'lifematters-c466d.firebaseapp.com',
    storageBucket: 'lifematters-c466d.firebasestorage.app',
    measurementId: 'G-FEV7L0C0PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOm6TCQHPIZmmWQlAESO6Bx3UuqKh-GpM',
    appId: '1:162639628951:android:b9d50937e7322c102637d2',
    messagingSenderId: '162639628951',
    projectId: 'lifematters-c466d',
    storageBucket: 'lifematters-c466d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1HeRCwblhlUXRP0TE0TQUepdsIu7pNpw',
    appId: '1:162639628951:ios:0fcbf9c537e784fa2637d2',
    messagingSenderId: '162639628951',
    projectId: 'lifematters-c466d',
    storageBucket: 'lifematters-c466d.firebasestorage.app',
    iosBundleId: 'com.example.lifeMatters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1HeRCwblhlUXRP0TE0TQUepdsIu7pNpw',
    appId: '1:162639628951:ios:0fcbf9c537e784fa2637d2',
    messagingSenderId: '162639628951',
    projectId: 'lifematters-c466d',
    storageBucket: 'lifematters-c466d.firebasestorage.app',
    iosBundleId: 'com.example.lifeMatters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcY5GjBFaJ-swvEJHBGsTiTE1qbumHIco',
    appId: '1:162639628951:web:617b6b6f8cf6c2512637d2',
    messagingSenderId: '162639628951',
    projectId: 'lifematters-c466d',
    authDomain: 'lifematters-c466d.firebaseapp.com',
    storageBucket: 'lifematters-c466d.firebasestorage.app',
    measurementId: 'G-RMCG1VRKFF',
  );

}