name: Deploy ArinaCave to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Inject environment variables
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
          echo "NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}" >> .env
          echo "project_name=projects/750656775698" >> .env
          echo "project_no=750656775698" >> .env

      - name: Build Flutter web
        run: flutter build web --base-href /arinacare/ --release --dart-define=GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} --dart-define=NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
      - name: Remove .env from build output (security)
        run: rm -f build/web/assets/.env

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web